config/routes.rb
Hdo::Application.routes.draw do

  #
  # api
  #

  namespace :api, defaults: {format: :hal} do
    root to: 'root#index'

    resources :issues, only: [:index, :show] do
      member {
        get 'promises'
        get 'timeline'
      }
    end

    resources :parliament_issues, only: [:index, :show], path: 'parliament-issues'
    resources :committees, only: [:index, :show]
    resources :districts, only: [:index, :show]
    resources :votes, only: [:index, :show]

    resources :parties, only: [:index, :show] do
      member {
        get 'logo'
        get 'representatives'
        get 'promises'
      }
    end

    resources :representatives, only: [:index, :show] do
      member { get 'image' }
    end

    resources :promises, only: [:index, :show]
    resources :propositions, only: [:index, :show]
    resources :governments, only: [:index, :show] do
      member {
        get 'parties'
        get 'promises'
      }
    end

    namespace :hdo do
      resources :users, only: [:index, :show]
      resources :blog, only: [:index]
    end

  end

  #
  # user sign-in
  #

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  #
  # admin
  #

  namespace :admin do
    resources :issues do
      collection do
        get  'promises/:ids'     => 'issues#promises'
        get  'propositions/:ids' => 'issues#propositions'
      end
    end

    resources :users
    resources :governments, except: :show
    resources :propositions, only: [:index, :edit, :update]
    resources :representatives, only: [:index, :edit, :update] do
      get 'activate'       => 'representatives#activate',       as: :activate
      get 'reset_password' => 'representatives#reset_password', as: :reset_password
    end

    # S&S
    resources :questions, only: [:index, :edit, :update] do
      member do
        put 'approve'        => 'questions#approve'
        put 'reject'         => 'questions#reject'

        get  'email/question/approved/rep'  => 'questions#question_approved_email_rep',  as: :question_approved_email_rep
        get  'email/question/approved/user' => 'questions#question_approved_email_user', as: :question_approved_email_user
        post 'email/question/rejected/user' => 'questions#question_rejected_email_user', as: :question_rejected_email_user
        get  'email/answer/approved/user'   => 'questions#answer_approved_email_user',   as: :answer_approved_email_user

        get  'answer' => 'questions#create_answer', as: :create_answer
      end
    end

    root to: "dashboard#index"
  end

  #
  # representative sign-in
  #

  devise_for :representative, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  devise_scope :representative do
    put  'representative/confirmation' => 'confirmations#update',         as: :update_representative_confirmation
    get  'representative/edit'         => 'devise/registrations#edit',    as: :edit_representative_registration
    put  'representative'              => 'devise/registrations#update',  as: :representative_registration
  end

  get  'representative'                       => 'representative#index',         as: :representative_root
  # get  'representative/questions/:id'         => 'representative#show_question', as: :representative_question
  # post 'representative/questions/:id/answers' => 'representative#create_answer', as: :representative_question_answers


  #
  # non-admin issues
  #

  resources :issues, only: [:index, :show, :votes] do
    member do
      get 'votes'      => 'issues#votes'
      get 'widget'     => 'widgets#issue'
      get 'admin_info' => 'issues#admin_info', as: :admin_info
      get 'next'       => 'issues#next'
    end
  end

  #
  # districts
  #

  resources :districts, only: [:index, :show]

  #
  # categories
  #

  resources :categories, only: [:index, :show]

  #
  # parties, committees
  #

  resources :parties,    only: [:index, :show] do
    member do
      get 'widget' => 'widgets#party'
    end
  end
  resources :committees, only: [:index, :show]

  #
  # promises
  #

  resources :promises, only: [:index, :show] do
    collection do
      get ':promises/widget' => 'widgets#promises', as: :widget
    end
  end


  #
  # parliament_issues
  #

  resources :parliament_issues, path: 'parliament-issues', only: [:index, :show]
  get 'parliament-issues/page/:page' => 'parliament_issues#index'

  #
  # representatives
  #

  resources :representatives, only: [:index, :show] do
    member do
      get 'widget'     => 'widgets#representative'
    end
  end

  get 'representatives/index/name'     => 'representatives#index_by_name', as: :representatives_by_name
  get 'representatives/index/party'    => 'representatives#index_by_party', as: :representatives_by_party
  get 'representatives/index/district' => 'representatives#index_by_district', as: :representatives_by_district

  #
  # propositions
  #

  resources :propositions, only: [:index, :show] do
    collection do
      get 'autotitle' => 'propositions#autotitle'
    end
  end

  #
  # votes
  #

  resources :votes, only: [:index, :show] do
    collection do
      get 'page/:page' => 'votes#index'
    end

    member do
      get 'propositions'
      get 'widget' => 'widgets#vote'
    end
  end


  #
  # widgets
  #

  get 'widgets'           => 'widgets#load', format: :js, as: :widget_load
  get 'widgets/topic'     => 'widgets#topic'
  get 'widgets/config'    => 'widgets#configure'

  #
  # home
  #

  get 'home/index'
  get 'home/contact'
  get 'home/people'
  get 'home/faq'        => 'home#faq', as: :home_faq
  get 'home/friends'

  get 'home/method'     => 'home#about'
  get 'home/about'      => 'home#about',    as: :home_about
  get 'home/terms'      => 'home#terms',    as: :home_terms
  get 'home/statutes'   => 'home#statutes', as: :home_statutes

  # deprecated
  get 'home/support', to: redirect('/')
  get 'home/member',  to: redirect('/')


  #
  # Q & A
  #

  resources :questions, only: [:index, :create, :show, :new] do
    collection do
      get 'conduct'
      get 'disabled' => 'questions#disabled', as: :disabled
    end
  end
  get 'questions/all/:category' => 'questions#all'

  #
  # norwegian aliases - don't overdo this without a proper solution
  #

  #
  # docs
  #

  get "docs/index"
  get "docs/analysis"

  #
  # global search
  #

  get 'search/all' => 'search#all', as: :search_all
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
  # get 'search/promises' => 'search#promises', as: :search_promises

  #
  # various
  #

  get 'robots.txt'    => 'home#robots'
  get 'info/revision' => 'home#revision'
  get 'healthz'       => 'home#healthz' # cheap health check for varnish/others
  get 'opensearch'    => 'home#opensearch'

  root to: 'home#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  hdo_caches_page :all, :autocomplete

  TYPE_ORDER = %w[
    issue
    topic
    representative
    parliament_issue
    proposition
    promise
  ]

  def all
    response = Hdo::Search::Searcher.new(params[:query], params[:size]).all

    @results = []

    if response.success?
      @results = response.results.
                          group_by { |e| e._type }.
                          sort_by { |t, _| TYPE_ORDER.index(t) || 10 }

      respond_to do |format|
        format.html
        format.json { render json: @results }
      end
    else
      flash.alert = t('app.errors.search')
    end
  end

  def autocomplete
    response = Hdo::Search::Searcher.new(params[:query]).autocomplete
    @results = []

    representative_icon = view_context.asset_path("representative.png")
    issue_icon          = view_context.asset_path("issue.png")

    if response.success?
      @results = response.results.map do |r|
        case r._type
        when 'representative'
          {
            type: r._type,
            img_src: representative_icon,
            url: representative_url(id: r.slug || r._id),
            full_name: r.full_name,
            party_name: r.latest_party.name
          }
        when 'issue'
          {
            type: r._type,
            img_src: issue_icon,
            url: issue_url(id: "#{r._id}-#{r.slug}"),
            title: r.title
          }
        end
      end.group_by { |e| e[:type] }

      respond_to do |format|
        format.json { render json: @results }
      end
    end
  end

  def promises
    response = Hdo::Search::Searcher.new(params[:query], params[:size]).promises

    respond_to do |format|
      format.json do
        if response.success?
          render json: response.results.map { |pr| pr._source.as_json.merge(id: pr._id)}
        else
          render json: {error: t('app.errors.search')}, status: 500
        end
      end
    end
  end
end

app/views/search/_issue_results.html.erb
<h3><%= Issue.model_name.human(count: 2).capitalize %></h3>

<ul>
  <% results.each do |r| %>
    <li><%= link_to r.title, issue_path("#{r._id}-#{r.slug}") %></li>
  <% end %>
</ul>

app/views/search/_parliament_issue_results.html.erb
<h3><%= ParliamentIssue.model_name.human(count: 2).capitalize %></h3>

<ul>
  <% results.sort_by { |r| r.last_update.to_date }.reverse.each do |r| %>
    <li><%= link_to r.summary, parliament_issue_path(r.slug) %></li>
  <% end %>
</ul>

app/views/search/_party_results.html.erb
<h3><%= Party.model_name.human(count: 2).capitalize %></h3>

<ul>
  <% results.sort_by(&:name).each do |r| %>
    <li><%= link_to r.name, party_path(r.slug) %></li>
  <% end %>
</ul>

app/views/search/_promise_results.html.erb
<h3><%= Promise.model_name.human(count: 2).capitalize %></h3>

<ul>
<% results.group_by { |e| e.party_names.to_sentence }.each do |party_names, promises| %>
  <% promises.each do |promise| %>
    <li>
      <%= link_to promise.body, promise_path(promise._id), class: 'promise-link' %>
      <span class="muted">(<%= promise.parliament_period_name %>)</span>
    </li>
  <% end %>
<% end %>
</ul>

app/views/search/_proposition_results.html.erb
<% results = results.reject { |r| r.description.empty? } %>

<% if results.any? %>
  <h3><%= Proposition.model_name.human(count: 2).capitalize %></h3>

  <ul>
    <% results.each do |r| %>
      <% if r.votes.first %>
        <li data-proposition-id="<%= r.id %>"><%= link_to r.simple_description || r.description, vote_path(r.votes.first.slug) %></li>
      <% else %>
        <li data-proposition-id="<%= r.id %>"><%= r.simple_description || r.description %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/search/_representative_results.html.erb
<h3><%= Representative.model_name.human(count: 2).capitalize %></h3>

<ul>
  <% results.sort_by(&:last_name).each do |r| %>
    <li>
      <%= link_to r.full_name, representative_path(r.slug) %>
      (<%= [r.district.name, r.latest_party && r.latest_party.name].join(", ") %>)
    </li>
  <% end %>
</ul>

app/views/search/_topic_results.html.erb
<h3><%= Topic.model_name.human(count: 2).capitalize %></h3>

<ul>
  <% results.sort_by(&:name).each do |r| %>
    <li>
      <%= link_to r.name, topic_path(r.slug) %>
    </li>
  <% end %>
</ul>

app/views/search/all.html.erb
<% if @results.empty? %>
  <%= t('app.search.no_hits') %>.
<% else %>
  <% @results.each do |type, items| %>
    <%= render partial: "#{type}_results", locals: { results: items } %>
  <% end %>
<% end %>

app/views/search/autocomplete.html.erb
<% if @results.empty? %>
  <%= t('app.search.no_hits') %>.
<% else %>
  <% @results.each do |type, items| %>
    <%= render partial: "#{type}_results", locals: { results: items } %>
  <% end %>
<% end %>