config/routes.rb
Hdo::Application.routes.draw do

  #
  # api
  #

  namespace :api, defaults: {format: :hal} do
    root to: 'root#index'

    resources :issues, only: [:index, :show] do
      member {
        get 'promises'
        get 'timeline'
      }
    end

    resources :parliament_issues, only: [:index, :show], path: 'parliament-issues'
    resources :committees, only: [:index, :show]
    resources :districts, only: [:index, :show]
    resources :votes, only: [:index, :show]

    resources :parties, only: [:index, :show] do
      member {
        get 'logo'
        get 'representatives'
        get 'promises'
      }
    end

    resources :representatives, only: [:index, :show] do
      member { get 'image' }
    end

    resources :promises, only: [:index, :show]
    resources :propositions, only: [:index, :show]
    resources :governments, only: [:index, :show] do
      member {
        get 'parties'
        get 'promises'
      }
    end

    namespace :hdo do
      resources :users, only: [:index, :show]
      resources :blog, only: [:index]
    end

  end

  #
  # user sign-in
  #

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  #
  # admin
  #

  namespace :admin do
    resources :issues do
      collection do
        get  'promises/:ids'     => 'issues#promises'
        get  'propositions/:ids' => 'issues#propositions'
      end
    end

    resources :users
    resources :governments, except: :show
    resources :propositions, only: [:index, :edit, :update]
    resources :representatives, only: [:index, :edit, :update] do
      get 'activate'       => 'representatives#activate',       as: :activate
      get 'reset_password' => 'representatives#reset_password', as: :reset_password
    end

    # S&S
    resources :questions, only: [:index, :edit, :update] do
      member do
        put 'approve'        => 'questions#approve'
        put 'reject'         => 'questions#reject'

        get  'email/question/approved/rep'  => 'questions#question_approved_email_rep',  as: :question_approved_email_rep
        get  'email/question/approved/user' => 'questions#question_approved_email_user', as: :question_approved_email_user
        post 'email/question/rejected/user' => 'questions#question_rejected_email_user', as: :question_rejected_email_user
        get  'email/answer/approved/user'   => 'questions#answer_approved_email_user',   as: :answer_approved_email_user

        get  'answer' => 'questions#create_answer', as: :create_answer
      end
    end

    root to: "dashboard#index"
  end

  #
  # representative sign-in
  #

  devise_for :representative, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  devise_scope :representative do
    put  'representative/confirmation' => 'confirmations#update',         as: :update_representative_confirmation
    get  'representative/edit'         => 'devise/registrations#edit',    as: :edit_representative_registration
    put  'representative'              => 'devise/registrations#update',  as: :representative_registration
  end

  get  'representative'                       => 'representative#index',         as: :representative_root
  # get  'representative/questions/:id'         => 'representative#show_question', as: :representative_question
  # post 'representative/questions/:id/answers' => 'representative#create_answer', as: :representative_question_answers


  #
  # non-admin issues
  #

  resources :issues, only: [:index, :show, :votes] do
    member do
      get 'votes'      => 'issues#votes'
      get 'widget'     => 'widgets#issue'
      get 'admin_info' => 'issues#admin_info', as: :admin_info
      get 'next'       => 'issues#next'
    end
  end

  #
  # districts
  #

  resources :districts, only: [:index, :show]

  #
  # categories
  #

  resources :categories, only: [:index, :show]

  #
  # parties, committees
  #

  resources :parties,    only: [:index, :show] do
    member do
      get 'widget' => 'widgets#party'
    end
  end
  resources :committees, only: [:index, :show]

  #
  # promises
  #

  resources :promises, only: [:index, :show] do
    collection do
      get ':promises/widget' => 'widgets#promises', as: :widget
    end
  end


  #
  # parliament_issues
  #

  resources :parliament_issues, path: 'parliament-issues', only: [:index, :show]
  get 'parliament-issues/page/:page' => 'parliament_issues#index'

  #
  # representatives
  #

  resources :representatives, only: [:index, :show] do
    member do
      get 'widget'     => 'widgets#representative'
    end
  end

  get 'representatives/index/name'     => 'representatives#index_by_name', as: :representatives_by_name
  get 'representatives/index/party'    => 'representatives#index_by_party', as: :representatives_by_party
  get 'representatives/index/district' => 'representatives#index_by_district', as: :representatives_by_district

  #
  # propositions
  #

  resources :propositions, only: [:index, :show] do
    collection do
      get 'autotitle' => 'propositions#autotitle'
    end
  end

  #
  # votes
  #

  resources :votes, only: [:index, :show] do
    collection do
      get 'page/:page' => 'votes#index'
    end

    member do
      get 'propositions'
      get 'widget' => 'widgets#vote'
    end
  end


  #
  # widgets
  #

  get 'widgets'           => 'widgets#load', format: :js, as: :widget_load
  get 'widgets/topic'     => 'widgets#topic'
  get 'widgets/config'    => 'widgets#configure'

  #
  # home
  #

  get 'home/index'
  get 'home/contact'
  get 'home/people'
  get 'home/faq'        => 'home#faq', as: :home_faq
  get 'home/friends'

  get 'home/method'     => 'home#about'
  get 'home/about'      => 'home#about',    as: :home_about
  get 'home/terms'      => 'home#terms',    as: :home_terms
  get 'home/statutes'   => 'home#statutes', as: :home_statutes

  # deprecated
  get 'home/support', to: redirect('/')
  get 'home/member',  to: redirect('/')


  #
  # Q & A
  #

  resources :questions, only: [:index, :create, :show, :new] do
    collection do
      get 'conduct'
      get 'disabled' => 'questions#disabled', as: :disabled
    end
  end
  get 'questions/all/:category' => 'questions#all'

  #
  # norwegian aliases - don't overdo this without a proper solution
  #

  #
  # docs
  #

  get "docs/index"
  get "docs/analysis"

  #
  # global search
  #

  get 'search/all' => 'search#all', as: :search_all
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
  # get 'search/promises' => 'search#promises', as: :search_promises

  #
  # various
  #

  get 'robots.txt'    => 'home#robots'
  get 'info/revision' => 'home#revision'
  get 'healthz'       => 'home#healthz' # cheap health check for varnish/others
  get 'opensearch'    => 'home#opensearch'

  root to: 'home#index'
end

app/controllers/admin/issues_controller.rb
# -*- coding: utf-8 -*-
class Admin::IssuesController < AdminController
  before_filter :fetch_issue, only: [:show, :edit, :update, :destroy]
  before_filter :fetch_sections, only: [:new, :create, :edit, :update]
  before_filter :authorize_edit, except: [:index, :show]
  before_filter :require_edit, except: [:index, :show]

  def index
    issues = Issue.order('frontpage IS FALSE, title').includes(:tags, :editor, :last_updated_by)
    @issues_by_status = issues.group_by { |e| e.status }
    
    respond_to do |format|
      format.html
      format.json { render json: @issues_by_status.values.flatten }
    end
  end

  def new
    @issue = Issue.new(status: 'in_progress')
    render 'edit'
  end

  def create
    @issue = Issue.new(params[:issue])
    @issue.last_updated_by = current_user

    if @issue.save
      save_issue
    else
      render text: @issue.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

  def show
    xhr_only {
      @parties             = Party.order(:name)
      @accountability      = @issue.accountability
      @promise_connections = @issue.promise_connections.includes(promise: :promisor)
      
      render layout: false
    }
  end

  def edit
  end

  def update
    logger.info "updating issue: #{params.to_json}"
    save_issue
  end

  def destroy
    @issue.destroy
    redirect_to admin_issues_url
  end

  def promises
    # xhr_only?
    json = params[:ids].split(',').map do |id|
      PromiseConnection.new(promise: Promise.find(id)).as_edit_view_json
    end

    render json: json
  end

  def propositions
    # xhr_only?
    json = params[:ids].split(',').map do |id|
      PropositionConnection.new(proposition: Proposition.find(id)).as_edit_view_json
    end

    render json: json
  end

  private

  def authorize_edit
    unless policy(@issue || Issue.new).edit?
      flash.alert = t('app.errors.unauthorized')
      redirect_to admin_root_path
    end
  end

  def fetch_issue
    @issue = Issue.find(params[:id])
  end

  def fetch_sections
    @sections = {
      intro: 'Intro',
      propositions: 'Forslag',
      promises: 'Løfter',
      positions: 'Posisjoner',
      party_comments: 'Partikommentarer'
    }
  end

  def save_issue
    ok = Hdo::IssueUpdater.new(@issue, params, current_user).update

    if ok
      PageCache.expire_issue(@issue)
      render json: { location: edit_admin_issue_path(@issue) }
    else
      render text: @issue.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

end

app/controllers/api/issues_controller.rb
module Api
  class IssuesController < ApiController
    before_filter :fetch_issue, except: :index

    def index
      respond_with Issue.
                    published.
                    order(:title).
                    page(params[:page] || 1).per(10)
    end

    def show
      respond_with @issue
    rescue ActiveRecord::RecordNotFound
      render json: {message: "could not find issue with id=#{params[:id]}"}, status: :not_found
    end

    def promises
      rel = @issue.promises.page(params[:page] || 1)

      respond_with rel, represent_with: PromisesRepresenter, issue: @issue
    end

    def timeline
      rel = @issue.proposition_connections.includes(:proposition => :votes).page(params[:page] || 1)

      respond_with rel, represent_with: PropositionConnectionsRepresenter, issue: @issue
    end

    private

    def fetch_issue
      @issue = Issue.published.find(params[:id])
    end
  end
end

app/controllers/issues_controller.rb
# encoding: UTF-8

class IssuesController < ApplicationController
  before_filter :fetch_issue, except: [:index, :admin_info, :votes]
  hdo_caches_page :index, :votes, :show

  ALERT = "Dette innholdet vil ikke bli oppdatert."

  def index
    @groups = Issue.published.in_tag_groups
    @groups = @groups.sort_by { |t, _| t.name }

    @extra_alert_message = ALERT
  end

  def show
    if policy(@issue).show?
      @extra_alert_message = ALERT
      fresh_when @issue, public: can_cache?
      @issue = IssueDecorator.decorate(@issue)
    else
      redirect_to new_user_session_path
    end
  end

  def votes
    redirect_to action: 'show', status: :moved_permanently
  end

  def admin_info
    if user_signed_in?
      fetch_issue
      @issue = IssueDecorator.decorate(@issue)
      render partial: 'admin_info'
    else
      head :ok
    end
  end

  private

  def fetch_issue
    @issue = Issue.find(params[:id])

    if params[:id] !~ /^\d/
      redirect_to url_for(id: @issue.to_param), status: :moved_permanently
    end
  end

end

app/helpers/admin/issues_helper.rb
# encoding: utf-8

module Admin::IssuesHelper

  def issue_options_for(model)
    # TODO(jari): this can be done with .pluck([:title, :id]) in rails 4
    opts = Issue.published.order(:title).select([:title, :id]).map { |e| [e.title, e.id] }
    options_for_select opts, selected: model.issues.map(&:id)
  end

  def proposer_options_for(model)
    proposers = Rails.cache.fetch('admin/propositions/proposers', expires_in: 1.day) do
      reps = Representative.all.map { |e| ["#{e.full_name} - #{e.external_id}", "#{e.class}-#{e.id}"]  }
      party = Party.all.map { |e| ["#{e.name} - #{e.external_id}", "#{e.class}-#{e.id}"] }

      party + reps
    end

      selected = model.proposers.map { |e| "#{e.class}-#{e.id}" }

    options_for_select proposers, selected: selected
  end

  def editor_options_for(issue)
    users = User.order(:name)

    editor = issue.new_record? ? current_user : issue.editor

    options_from_collection_for_select(users, 'id', 'name', selected: editor.try(:id))
  end

  def all_tags
    ActsAsTaggableOn::Tag.select(:name).all.map(&:name)
  end

  def connected_issues_for(proposition)
    (proposition.issues - [@issue])
  end

  def promise_status_for(promise)
    conn = promise.promise_connections.find { |pc| pc.issue_id == @issue.id }
    conn ? conn.status : 'unrelated'
  end

  def parliament_period_options_for(position)
    data = ParliamentPeriod.order(:start_date).reverse_order.map { |e| [e.name, e.id] }

    options_for_select data, selected: position.parliament_period.try(:id)
  end

  def promise_states
    [PromiseConnection::STATES, PromiseConnection::UNRELATED_STATE].flatten
  end

  def disable_promise_state?(state, promise)
    promise.parliament_period_name != '2009-2013' && %[kept partially_kept broken].include?(state)
  end

  def issues_for_promise(promise)
    pcs = promise.promise_connections.select { |pc| pc.issue.id != @issue.id }

    out = ''

    if pcs.any?
      out = "#{I18n.t 'app.issues.edit.promise_used_in'} "
      out << pcs.map { |pc| link_to(pc.issue.title, pc.issue, target: '_blank') }.to_sentence
    end

    out.html_safe
  end

  def promise_counts_for(party)
    pcs = @promise_connections.select { |e| e.promise.parties.include?(party) }

    counts = Hash.new(0).with_indifferent_access
    counts[:total] = pcs.size
    counts[:used] = 0

    pcs.each do |pc|
      counts[:used] += 1
      counts[pc.status.to_sym] += 1
    end

    counts
  end

  def with_promise_status(promises)
    promises.sort_by(&:parliament_period_name).map { |pr| [pr, promise_status_for(pr)] }.sort_by { |_, status| status }
  end

  def party_options(opts = {})
    options_for_select(Party.order(:name).map { |p| [p.name, p.id] }, opts[:selected])
  end

  def parliament_period_options(opts = {})
    options_for_select(ParliamentPeriod.order(:start_date).reverse_order.map { |p| [p.name, p.id] }, opts[:selected])
  end
end

app/views/issues/_admin_info.html.erb
<div id="admin-info" class="alert alert-warning">
  Denne saken er <strong><%= @issue.status_text.downcase %></strong>.

  <div class="row-fluid">
    <div class="span8">
      <%= Issue.human_attribute_name :editor %> er <strong><%= @issue.editor_name %></strong>,
      <%= Issue.human_attribute_name(:last_updated_by).downcase %> <strong><%= @issue.last_updated_by_name %></strong> for <%= @issue.time_since_updated %> siden.
    </div>

    <div class="span4 rightify">
      <% if policy(@issue).edit? %>
        <%= link_to t('app.edit'), edit_admin_issue_path(@issue), class: 'btn btn-small' %>
        <button class="btn btn-small" data-modal-url="<%= admin_issue_path(@issue) %>" href="#view-scores"><%= t 'app.issues.view_scores' %></button>
      <% end %>
    </div>
  </div>
</div>

<div id="view-scores" class="modal hide fade" tabindex="-1"></div>
<script>HDO.xhrModal($('#admin-info button'), {width: '30%'})</script>

app/views/issues/_aside.html.erb
<aside class="muted">
  <%= Issue.human_attribute_name(:updated_at) %> <%= issue.updated_at %>.

  <span class="issue-tags">
    <% issue.tags.each do |tag| %>
      <%= link_to tag.name, issues_path(anchor: "tag-#{tag.slug}") %>
    <% end %>
  </span>
</aside>

app/views/issues/_edit_buttons.html.erb
<div class="form-actions">
  <div class="pull-left">
    <%= form.submit t('app.previous'), name: 'previous', disabled: disable_prev %>
    <%= form.submit t('app.next'), disabled: disable_next %>
  </div>

  <div class="pull-right">
    <%= link_to t('app.cancel'), issues_path, :class => 'btn btn-danger' %>
    <%= form.submit t('app.done'), class: 'btn btn-primary', name: 'finish' %>
  </div>
</div>

app/views/issues/_form.html.erb
<%= twitter_bootstrap_form_for @issue do |form| %>
  <%= form.hidden_field :lock_version %>
  <% if @issue_steps %>
    <%= render partial: "step_pagination", locals: { form: form, issue_steps: @issue_steps } %>
  <% end %>
  <%= render partial: "edit_buttons", locals: { form: form, disable_prev: @disable_prev, disable_next: @disable_next } %>
  <%= render partial: "#{edit_steps.current}_step", locals: { form: form } %>
<% end %>

app/views/issues/_issue_index_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= Issue.human_attribute_name :title %></th>
      <th><%= Issue.human_attribute_name :updated_at %></th>
      <th><%= Topic.model_name.human(count: 2).capitalize %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% issues.each do |issue| %>
      <tr>
        <td>
          <p><%= link_to issue.title, issue %></p>
        </td>
        <td><p><%= l issue.updated_at.localtime %></p> <small class="muted"><%= issue.last_updated_by_name %></small></td>
        <td>
          <ul>
          <% issue.topics.each do |topic| %>
            <li><%= link_to topic.name, topic %></li>
          <% end %>
          </ul>
        </td>
        <td>
          <%= link_to t('app.edit'), edit_issue_path(issue), class: 'btn btn-small' %>
          <%= link_to t('app.destroy'), issue, method: :delete, data: { confirm: t('app.issues.edit.confirm_destroy', title: issue.title) }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issues/_period_summary.html.erb
<div class="new-positions">
  <div class="row-fluid">
    <div class="span8 offset2">
      <h3><%= period.name %> oppsummert</h3>
    </div>
  </div>

  <!-- promises -->
  <div class="row-fluid <%= 'hidden' if period.promisors.empty? %>">
    <div class="row-fluid">
      <div class="span9 offset2">
        <h4>Hva har blitt lovet</h4>
      </div>
    </div>

    <% period.promisors.each do |promisor| %>
      <div class="row-fluid group">
        <div class="span1 offset1">
          <% promisor.parties.reverse.each do |party| %>
            <%= image_tag party.logo.versions[:medium], alt: "#{party.name}s logo" %>
          <% end %>
        </div>

        <div class="span10 promise-list">
          <% if promisor.expandable? %>
            <span class="expandable <%= 'muted' if promisor.teaser_connection.related? %>"></span>
          <% else %>
            <span style="padding: 0 5px;">&nbsp;&nbsp;&nbsp;</span>
          <% end %>

          <span class="teaser <%= 'muted' if promisor.teaser_connection.related? %>">
            <%= promisor.teaser %>
          </span>

          <div class="promises">
            <ul class="unstyled">
              <% promisor.promises.each do |promise, connection| %>
                <li class="<%= 'muted' if connection.related? %>">
                  <%= promise.body %>
                  <%= link_to promise, target: '_blank' do %>
                    <%= image_tag 'link.png', width: '12' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <hr class="divider">
  </div>

  <!-- positions -->
  <div class="row-fluid">
    <div class="row-fluid">
      <div class="span9 offset2">
        <h4>Hva har blitt stemt</h4>
        <small class="muted"><%= period.explanation %></small>
      </div>
    </div>

    <% if period.positions.empty? %>
      <div class="row-fluid">
        <i class="offset2">Vi har foreløpig ikke nok relevante avstemninger i denne perioden til å oppsummere posisjonene.</i>
      </div>
    <% else %>
      <% period.positions.each do |position| %>
        <div class="row-fluid group position">
          <div class="span1 offset1">
            <% position.parties.reverse.each do |party| %>
              <%= image_tag party.logo.versions[:medium], alt: "#{party.name}s logo" %>
            <% end %>
          </div>

          <div class="span9">
            <div><strong><%= position.title %></strong></div>
            <div><%= position.description %></div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <hr class="divider">

  <!-- accountability -->
  <div class="row-fluid">
    <div class="span9 offset2">
      <h4>Vår vurdering</h4>
    </div>
  </div>

  <% if period.positions.empty? %>
    <div class="row-fluid">
      <i class="offset2">Vi har foreløpig ikke nok relevante avstemninger i denne perioden til å vurdere løftebrudd.</i>
    </div>
  <% else %>
    <% period.positions.flat_map(&:parties).uniq.sort_by(&:name).each do |party| %>
      <div class="row-fluid group">
        <div class="span1 offset1"><%= image_tag party.logo.versions[:medium], alt: "#{party.name}s logo" %></div>
        <div class="span10">
          <%= party.accountability %>

          <% if party.comment.present? %>
            <small>
              <a data-toggle="collapse" href="#<%= [party.slug, period.name, 'comments'].join('-') %>"><%= party.name %>s kommentar</a>
            </small>

            <div class="collapse party-comments" id="<%= [party.slug, period.name, 'comments'].join('-') %>">
              <small class="muted">Kommentar fra <%= party.name %>, <%= l party.comment.created_at, format: :text %></small>
              <blockquote><%= markdown(party.comment.body).html_safe %></blockquote>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/issues/_votes_step.html.erb
<h3>
  <%= t('app.issues.edit.connected_votes') %>
  <small class="pull-right"><%= t('app.counts.vote', count: @votes_and_connections.size).html_safe %></small>
</h3>

<div class="vote-container">
  <%= render partial: 'votes_list', locals: { votes_and_connections: @votes_and_connections} %>
</div>

<div class="well form-horizontal">
  <h3><%= t('app.issues.edit.find_votes') %></h3>

  <div class="control-group">
    <label for="keyword"><%= t('app.issues.edit.keyword') %>:</label>
    <input id="keyword" type="text" class="input-medium search-query">
  </div>

  <div class="control-group">
    <label for="filter"><%= t('app.issues.edit.filter') %>:</label>

    <select id="filter">
      <option value="selected-categories"><%= t('app.issues.edit.selected_categories') %></option>
      <option value="all"><%= t('app.issues.edit.all') %></option>
      <option value="not-connected"><%= t('app.issues.edit.not_connected') %></option>
    </select>
  </div>

  <div class="control-group">
    <button id="reset" type="submit" class="btn btn-warning"><%= t('app.issues.edit.reset') %></button>
    <button id="fetch-votes" type="submit" class="btn btn-info"><%= t('app.issues.edit.fetch_votes') %></button>
  </div>
</div>

<h3>
  <%= t('app.issues.edit.search_result') %>
  <small class="pull-right" id="result-count"></small>
</h3>


<%= spinner_tag %>
<div class="vote-container" id="result"></div>

<%= content_for :document_ready do %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    var url = <%= issue_votes_search_path(@issue).to_json.html_safe %>;

    HDO.voteSearcher.create(url).init();
    HDO.votePropositionFetcher.create().init();
  });
</script>
<% end %>

app/views/issues/index.html.erb
<% page_title "#{t('app.issues.title')} - #{t('app.title')}" %>

<section class="top-issues">
  <% @groups.each do |tag, issues| %>
    <div class="row-fluid" id="tag-<%= tag.slug %>">
      <h3 class="top-issues-caption"><%= tag.name %></h3>
      <% issues.each_slice(3) do |issues| %>
        <div class="row-fluid">
        <% issues.each do |issue| %>
          <article class="issue span4">
          <%= link_to issue do %>
            <h4><%= issue.title %></h4>
            <p>
              <%= awesome_truncate issue.description, 400 %>
              <span class="read-more"><%= t('app.read_more') %></span>
            </p>
          <% end %>
          </article>
        <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</section>

app/views/issues/show.html.erb
<% page_title "#{@issue.title} - #{t('app.issues.title')} - #{t('app.title')}" %>
<% metadata[:description] = @issue.description %>
<% metadata[:type] = 'article' %>
<% metadata[:url] = issue_url(@issue) %>

<div id="admin-info"></div>
<%= content_for :document_ready do %>
  <script>
  $(document).ready(function() {
    if (HDO.ssl && 'https:' != document.location.protocol) {
      return;
    }

    $.ajax({
      url: '<%= admin_info_issue_path(@issue) %>',
      type: 'GET',
      dataType: 'html',
      success: function(data, textStatus, xhr) { $("#admin-info").html(data); }
    });
  });
  </script>
<% end %>

<article class="issue-timeline">
  <div class="page-header">
    <h1 class="issue-title"><%= @issue.title %></h1>
    <div class="row-fluid">
      <div class="span6">
        <%= render partial: 'aside', locals: { issue: @issue } %>
      </div>

      <div class="pull-right">
        <%= render partial: 'shared/social_sharing' %>
      </div>
    </div>
  </div>

  <p class="issue-description"><%= @issue.description %></p>

  <% @issue.periods.each do |period| %>
    <%= render partial: 'period_summary', locals: {period: period} %>

    <div class="timeline">
      <% period.years.each do |year| %>
        <div class="yearmarker"><%= year.year %></div>

        <% year.days.each do |day| %>
          <div class="row-fluid timeline-entry">
            <div class="span6"></div>
            <div class="date span6">
              <div class="day"><%= day.day %></div>
              <div class="month"><%= day.month %></div>
            </div>
          </div>

          <% day.votes.in_groups_of(2, false).each do |votes| %>
            <div class="row-fluid votes">
            <% votes.each do |vote| %>
              <div class="span6 vote">
                <%= link_to vote.title_with_fallback, vote.vote, class: 'vote-title' %>
                <div class="vote-detail"><%= vote.html_comment.html_safe %></div>

                <div class="row-fluid">
                  <small>
                    <div class="span6">
                      <strong>For</strong> <small>(<%= vote.vote.stats.for_percent %>%)</small>
                      <ul class="unstyled">
                        <% vote.proposition.decorate.supporters.map(&:name).each do |name| %>
                          <li><%= name %></li>
                        <% end %>
                      </ul>
                    </div>

                    <div class="span6">
                      <strong>Mot</strong> <small>(<%= vote.vote.stats.against_percent %>%)</small>
                      <ul class="unstyled">
                        <% vote.proposition.decorate.opposers.map(&:name).each do |name| %>
                          <li><%= name %></li>
                        <% end %>
                      </ul>
                    </div>
                  </small>
                </div>

                <hr class="soften">
              </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</article>

<% content_for :document_ready do %>
  <script type="text/javascript" charset="utf-8">
    var lists = $(".promise-list")

    lists.on('click', '.expandable, .expanded, .teaser', function (e) {
      var dt = $(e.delegateTarget);

      dt.find('.expandable, .expanded').toggleClass('expandable expanded');
      dt.find('.teaser, .promises').toggle();
    });
  </script>
<% end %>