config/routes.rb
Hdo::Application.routes.draw do

  #
  # api
  #

  namespace :api, defaults: {format: :hal} do
    root to: 'root#index'

    resources :issues, only: [:index, :show] do
      member {
        get 'promises'
        get 'timeline'
      }
    end

    resources :parliament_issues, only: [:index, :show], path: 'parliament-issues'
    resources :committees, only: [:index, :show]
    resources :districts, only: [:index, :show]
    resources :votes, only: [:index, :show]

    resources :parties, only: [:index, :show] do
      member {
        get 'logo'
        get 'representatives'
        get 'promises'
      }
    end

    resources :representatives, only: [:index, :show] do
      member { get 'image' }
    end

    resources :promises, only: [:index, :show]
    resources :propositions, only: [:index, :show]
    resources :governments, only: [:index, :show] do
      member {
        get 'parties'
        get 'promises'
      }
    end

    namespace :hdo do
      resources :users, only: [:index, :show]
      resources :blog, only: [:index]
    end

  end

  #
  # user sign-in
  #

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  #
  # admin
  #

  namespace :admin do
    resources :issues do
      collection do
        get  'promises/:ids'     => 'issues#promises'
        get  'propositions/:ids' => 'issues#propositions'
      end
    end

    resources :users
    resources :governments, except: :show
    resources :propositions, only: [:index, :edit, :update]
    resources :representatives, only: [:index, :edit, :update] do
      get 'activate'       => 'representatives#activate',       as: :activate
      get 'reset_password' => 'representatives#reset_password', as: :reset_password
    end

    # S&S
    resources :questions, only: [:index, :edit, :update] do
      member do
        put 'approve'        => 'questions#approve'
        put 'reject'         => 'questions#reject'

        get  'email/question/approved/rep'  => 'questions#question_approved_email_rep',  as: :question_approved_email_rep
        get  'email/question/approved/user' => 'questions#question_approved_email_user', as: :question_approved_email_user
        post 'email/question/rejected/user' => 'questions#question_rejected_email_user', as: :question_rejected_email_user
        get  'email/answer/approved/user'   => 'questions#answer_approved_email_user',   as: :answer_approved_email_user

        get  'answer' => 'questions#create_answer', as: :create_answer
      end
    end

    root to: "dashboard#index"
  end

  #
  # representative sign-in
  #

  devise_for :representative, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  devise_scope :representative do
    put  'representative/confirmation' => 'confirmations#update',         as: :update_representative_confirmation
    get  'representative/edit'         => 'devise/registrations#edit',    as: :edit_representative_registration
    put  'representative'              => 'devise/registrations#update',  as: :representative_registration
  end

  get  'representative'                       => 'representative#index',         as: :representative_root
  # get  'representative/questions/:id'         => 'representative#show_question', as: :representative_question
  # post 'representative/questions/:id/answers' => 'representative#create_answer', as: :representative_question_answers


  #
  # non-admin issues
  #

  resources :issues, only: [:index, :show, :votes] do
    member do
      get 'votes'      => 'issues#votes'
      get 'widget'     => 'widgets#issue'
      get 'admin_info' => 'issues#admin_info', as: :admin_info
      get 'next'       => 'issues#next'
    end
  end

  #
  # districts
  #

  resources :districts, only: [:index, :show]

  #
  # categories
  #

  resources :categories, only: [:index, :show]

  #
  # parties, committees
  #

  resources :parties,    only: [:index, :show] do
    member do
      get 'widget' => 'widgets#party'
    end
  end
  resources :committees, only: [:index, :show]

  #
  # promises
  #

  resources :promises, only: [:index, :show] do
    collection do
      get ':promises/widget' => 'widgets#promises', as: :widget
    end
  end


  #
  # parliament_issues
  #

  resources :parliament_issues, path: 'parliament-issues', only: [:index, :show]
  get 'parliament-issues/page/:page' => 'parliament_issues#index'

  #
  # representatives
  #

  resources :representatives, only: [:index, :show] do
    member do
      get 'widget'     => 'widgets#representative'
    end
  end

  get 'representatives/index/name'     => 'representatives#index_by_name', as: :representatives_by_name
  get 'representatives/index/party'    => 'representatives#index_by_party', as: :representatives_by_party
  get 'representatives/index/district' => 'representatives#index_by_district', as: :representatives_by_district

  #
  # propositions
  #

  resources :propositions, only: [:index, :show] do
    collection do
      get 'autotitle' => 'propositions#autotitle'
    end
  end

  #
  # votes
  #

  resources :votes, only: [:index, :show] do
    collection do
      get 'page/:page' => 'votes#index'
    end

    member do
      get 'propositions'
      get 'widget' => 'widgets#vote'
    end
  end


  #
  # widgets
  #

  get 'widgets'           => 'widgets#load', format: :js, as: :widget_load
  get 'widgets/topic'     => 'widgets#topic'
  get 'widgets/config'    => 'widgets#configure'

  #
  # home
  #

  get 'home/index'
  get 'home/contact'
  get 'home/people'
  get 'home/faq'        => 'home#faq', as: :home_faq
  get 'home/friends'

  get 'home/method'     => 'home#about'
  get 'home/about'      => 'home#about',    as: :home_about
  get 'home/terms'      => 'home#terms',    as: :home_terms
  get 'home/statutes'   => 'home#statutes', as: :home_statutes

  # deprecated
  get 'home/support', to: redirect('/')
  get 'home/member',  to: redirect('/')


  #
  # Q & A
  #

  resources :questions, only: [:index, :create, :show, :new] do
    collection do
      get 'conduct'
      get 'disabled' => 'questions#disabled', as: :disabled
    end
  end
  get 'questions/all/:category' => 'questions#all'

  #
  # norwegian aliases - don't overdo this without a proper solution
  #

  #
  # docs
  #

  get "docs/index"
  get "docs/analysis"

  #
  # global search
  #

  get 'search/all' => 'search#all', as: :search_all
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
  # get 'search/promises' => 'search#promises', as: :search_promises

  #
  # various
  #

  get 'robots.txt'    => 'home#robots'
  get 'info/revision' => 'home#revision'
  get 'healthz'       => 'home#healthz' # cheap health check for varnish/others
  get 'opensearch'    => 'home#opensearch'

  root to: 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role, :description, :active, :board, :title

  has_many :last_updated_issues, foreign_key: 'last_updated_by_id', class_name: 'Issue'
  has_many :issues, foreign_key: 'editor_id', order: :title

  ROLES = %w[contributor admin superadmin]
  validates :role, presence: true, inclusion: { in: ROLES }

  scope :active, -> { where(active: true) }

  def admin?
    role == 'admin'
  end

  def superadmin?
    role == 'superadmin'
  end

  def contributor?
    role == 'contributor'
  end

  def first_name
    name.split(' ').first
  end

  def percentage_of_issues
    if Issue.count.zero?
      0
    else
      issues.size * 100 / Issue.count
    end
  end
end

app/views/topics/_form.html.erb
<%= twitter_bootstrap_form_for topic, :html => {:multipart => true} do |form| %>
  <%# form.inputs do %>
    <div class="well">
      <%= form.text_field :name %>
    </div>
  <%# end %>

  <h1><%= Issue.model_name.human(count: 2).capitalize %></h1>
  <div class="well">
    <% @issues.each do |issue| %>
      <div class="row">
        <div class="span6">
          <label class="checkbox">
            <%= check_box_tag "topic[issue_ids][]", issue.id, topic.issues.include?(issue) %>
            <strong><%= issue.title.capitalize %></strong>
          </label>
        </div>
      </div>
    <% end %>
  </div>

  <h1><%= Topic.human_attribute_name :image %></h1>

  <div class="well">
    <%= form.file_field :image %>
    <%= image_tag topic.image.thumb('100x100').url if topic.image_uid %>
  </div>

  <div class="pull-right">
    <%= link_to t('app.cancel'), issues_path, :class => 'btn btn-danger' %>
    <%= form.submit t('app.done'), class: 'btn btn-primary', name: 'finish' %>
  </div>

<% end %>

app/views/topics/_parties_list.html.erb
<% parties.each do |party| %>
  <div class="row-fluid">
    <div class="span2"><%= image_tag party.image.thumb('150x150').url, alt: "#{party.name}s logo" %></div>
    <div class="span10">
      <h2><%= topic.stats.text_for(party) %></h2>
      <h3 class="pull-right"><%= topic.stats.score_for(party) %>%</h3>

      <% if promises = promises_by_party[party] %>
      <h5>I partiprogrammet har <%= party.name %> lovet følgende:</h5>
      <ul>
        <% promises.each do |promise| %>
        <li><%= promise.body %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
  <div class="row-fluid">
    <%= link_to "Se alle #{party.external_id}s løfter", party_path(party), class: 'pull-right' %>
  </div>

  <hr class="soften">
<% end %>

app/views/topics/index.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= Topic.human_attribute_name :name %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.name, topic %></td>
        <td>
          <%= link_to t('.new', :default => t("helpers.links.edit")), edit_topic_path(topic), :class => 'btn' %>
        </td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")), topic, method: :delete, data: { confirm: Topic.human_attribute_name(:confirm_destroy) }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")), new_topic_path, :class => 'btn btn-primary' %>