config/routes.rb
Hdo::Application.routes.draw do

  #
  # api
  #

  namespace :api, defaults: {format: :hal} do
    root to: 'root#index'

    resources :issues, only: [:index, :show] do
      member {
        get 'promises'
        get 'timeline'
      }
    end

    resources :parliament_issues, only: [:index, :show], path: 'parliament-issues'
    resources :committees, only: [:index, :show]
    resources :districts, only: [:index, :show]
    resources :votes, only: [:index, :show]

    resources :parties, only: [:index, :show] do
      member {
        get 'logo'
        get 'representatives'
        get 'promises'
      }
    end

    resources :representatives, only: [:index, :show] do
      member { get 'image' }
    end

    resources :promises, only: [:index, :show]
    resources :propositions, only: [:index, :show]
    resources :governments, only: [:index, :show] do
      member {
        get 'parties'
        get 'promises'
      }
    end

    namespace :hdo do
      resources :users, only: [:index, :show]
      resources :blog, only: [:index]
    end

  end

  #
  # user sign-in
  #

  devise_for :users, controllers: { sessions: 'sessions', passwords: 'passwords' }

  #
  # admin
  #

  namespace :admin do
    resources :issues do
      collection do
        get  'promises/:ids'     => 'issues#promises'
        get  'propositions/:ids' => 'issues#propositions'
      end
    end

    resources :users
    resources :governments, except: :show
    resources :propositions, only: [:index, :edit, :update]
    resources :representatives, only: [:index, :edit, :update] do
      get 'activate'       => 'representatives#activate',       as: :activate
      get 'reset_password' => 'representatives#reset_password', as: :reset_password
    end

    # S&S
    resources :questions, only: [:index, :edit, :update] do
      member do
        put 'approve'        => 'questions#approve'
        put 'reject'         => 'questions#reject'

        get  'email/question/approved/rep'  => 'questions#question_approved_email_rep',  as: :question_approved_email_rep
        get  'email/question/approved/user' => 'questions#question_approved_email_user', as: :question_approved_email_user
        post 'email/question/rejected/user' => 'questions#question_rejected_email_user', as: :question_rejected_email_user
        get  'email/answer/approved/user'   => 'questions#answer_approved_email_user',   as: :answer_approved_email_user

        get  'answer' => 'questions#create_answer', as: :create_answer
      end
    end

    root to: "dashboard#index"
  end

  #
  # representative sign-in
  #

  devise_for :representative, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  devise_scope :representative do
    put  'representative/confirmation' => 'confirmations#update',         as: :update_representative_confirmation
    get  'representative/edit'         => 'devise/registrations#edit',    as: :edit_representative_registration
    put  'representative'              => 'devise/registrations#update',  as: :representative_registration
  end

  get  'representative'                       => 'representative#index',         as: :representative_root
  # get  'representative/questions/:id'         => 'representative#show_question', as: :representative_question
  # post 'representative/questions/:id/answers' => 'representative#create_answer', as: :representative_question_answers


  #
  # non-admin issues
  #

  resources :issues, only: [:index, :show, :votes] do
    member do
      get 'votes'      => 'issues#votes'
      get 'widget'     => 'widgets#issue'
      get 'admin_info' => 'issues#admin_info', as: :admin_info
      get 'next'       => 'issues#next'
    end
  end

  #
  # districts
  #

  resources :districts, only: [:index, :show]

  #
  # categories
  #

  resources :categories, only: [:index, :show]

  #
  # parties, committees
  #

  resources :parties,    only: [:index, :show] do
    member do
      get 'widget' => 'widgets#party'
    end
  end
  resources :committees, only: [:index, :show]

  #
  # promises
  #

  resources :promises, only: [:index, :show] do
    collection do
      get ':promises/widget' => 'widgets#promises', as: :widget
    end
  end


  #
  # parliament_issues
  #

  resources :parliament_issues, path: 'parliament-issues', only: [:index, :show]
  get 'parliament-issues/page/:page' => 'parliament_issues#index'

  #
  # representatives
  #

  resources :representatives, only: [:index, :show] do
    member do
      get 'widget'     => 'widgets#representative'
    end
  end

  get 'representatives/index/name'     => 'representatives#index_by_name', as: :representatives_by_name
  get 'representatives/index/party'    => 'representatives#index_by_party', as: :representatives_by_party
  get 'representatives/index/district' => 'representatives#index_by_district', as: :representatives_by_district

  #
  # propositions
  #

  resources :propositions, only: [:index, :show] do
    collection do
      get 'autotitle' => 'propositions#autotitle'
    end
  end

  #
  # votes
  #

  resources :votes, only: [:index, :show] do
    collection do
      get 'page/:page' => 'votes#index'
    end

    member do
      get 'propositions'
      get 'widget' => 'widgets#vote'
    end
  end


  #
  # widgets
  #

  get 'widgets'           => 'widgets#load', format: :js, as: :widget_load
  get 'widgets/topic'     => 'widgets#topic'
  get 'widgets/config'    => 'widgets#configure'

  #
  # home
  #

  get 'home/index'
  get 'home/contact'
  get 'home/people'
  get 'home/faq'        => 'home#faq', as: :home_faq
  get 'home/friends'

  get 'home/method'     => 'home#about'
  get 'home/about'      => 'home#about',    as: :home_about
  get 'home/terms'      => 'home#terms',    as: :home_terms
  get 'home/statutes'   => 'home#statutes', as: :home_statutes

  # deprecated
  get 'home/support', to: redirect('/')
  get 'home/member',  to: redirect('/')


  #
  # Q & A
  #

  resources :questions, only: [:index, :create, :show, :new] do
    collection do
      get 'conduct'
      get 'disabled' => 'questions#disabled', as: :disabled
    end
  end
  get 'questions/all/:category' => 'questions#all'

  #
  # norwegian aliases - don't overdo this without a proper solution
  #

  #
  # docs
  #

  get "docs/index"
  get "docs/analysis"

  #
  # global search
  #

  get 'search/all' => 'search#all', as: :search_all
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
  # get 'search/promises' => 'search#promises', as: :search_promises

  #
  # various
  #

  get 'robots.txt'    => 'home#robots'
  get 'info/revision' => 'home#revision'
  get 'healthz'       => 'home#healthz' # cheap health check for varnish/others
  get 'opensearch'    => 'home#opensearch'

  root to: 'home#index'
end

app/views/shared/_edit_password.html.erb
<h2>Endre passord</h2>
<p>Her kan du sette et nytt passord dersom du har glemt ditt gamle.</p>

<%= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :reset_password_token %>

  <div><%= f.label :password, "Nytt passord" %>
  <%= f.password_field :password, :autofocus => true %></div>

  <div><%= f.label :password_confirmation, "Bekrefte nytt passord" %>
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sett nytt passord" %></div>
<% end %>

<%= link_to t('app.login'), new_user_session_path %>

app/views/shared/_ga.html.erb
<!-- analytics.js -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-19569290-4', 'holderdeord.no');
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');
</script>

app/views/shared/_global_search.html.erb
<form class="form-search navbar-search pull-right" method="GET" action="<%= search_all_path %>">
  <div class="input-append">
    <input class="span2 search-query" tabindex=1 name="query" id="appendedInputButton" type="text" autocomplete="off">
    <button class="btn" type="submit">Søk</button>
  </div>
</form>

app/views/shared/_issue_positions.html.erb
<div class="row-fluid">
  <% [:for, :for_and_against, :against].each do |key| %>
    <div class="span4">
      <h4 class="lead"><%= t "app.#{key}" %></h4>

      <% if issue_groups[key].blank? %>
        <p><%= t 'app.issues.none' %>.</p>
      <% else %>
        <ul class="issue-list">
          <% issue_groups[key].each do |issue| %>
            <li>
              <%= link_to issue do %>
                <span class="issue-<%= key %>"><%= t "app.#{key}" %></span>
                <span class="issue-list-text">
                  <%= t 'app.lang.infinitive_particle' %>
                  <%= issue.downcased_title %>.
                </span>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>

    </div>
  <% end %>
</div>

app/views/shared/_navigator_mobile_controls.html.erb
<div class="row-fluid visible-phone">
  <a href="#" id="show-filters">&#9654; Vis søk og filtre</a>
  <a href="#" id="hide-filters" class="hidden">&#9660; Skjul søk og filtre</a>
  (<%= number_with_delimiter search.hits, delimiter: ' ' -%></strong> <%= search.model.model_name.human(count: 2) %>)
</div>

<%= content_for :document_ready do %>
<script>
  $(function() {
    var showLink = $("#show-filters"),
        hideLink = $("#hide-filters"),
        navs     = $(".navigators");

    showLink.click(function(e) {
      e.preventDefault();

      showLink.toggleClass('hidden');
      hideLink.toggleClass('hidden');

      navs.toggleClass('hidden-phone');
    });

    $("#hide-filters").click(function(e) {
      e.preventDefault();

      hideLink.toggleClass('hidden');
      showLink.toggleClass('hidden');

      navs.toggleClass('hidden-phone');
    });
  });
  </script>
<% end -%>

app/views/shared/_navigators.html.erb
<%= form_tag search.url, method: :get, class: 'form-search' do -%>
  <% search.query.except(:q).each do |key, value| %>
    <%= hidden_field_tag key, value -%>
  <% end %>

  <% search.navigators.each do |nav| %>
    <div class="navigator navigator-<%= nav.param %>">
      <h4><%= nav.title %></h4>

      <% if nav.keyword? %>
        <%= text_field_tag 'q', nav.value, tabindex: 2, type: 'search', class: 'search-query' %>
      <% elsif nav.facet? %>

        <ul class="unstyled">
          <% nav.each_term do |term| %>
            <li class="term <%= 'active' if term.active %>">
              <% if term.active %>
                <%= link_to 'X', term.clear_url, class: 'pull-right' %>
              <% end %>

              <%= link_to term.name.to_s.truncate(50), term.filter_url %> (<%= term.count %>)
            </li>
          <% end %>
        </ul>
      <% elsif nav.boolean? %>
        <div class="term <%= 'active' if nav.active? %>">
          <% if nav.active? %>
            <%= link_to 'X', nav.clear_url, class: 'pull-right' %>
          <% end %>

          <%= link_to nav.title, nav.filter_url %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end -%>



<%= content_for :document_ready do %>
<script>
  $(function() {
    // focus search field with forward slash
    // everyone should have this
    $(document).keypress(function(e) {
      if (e.which == 47 && e.target.tagName !== 'INPUT') {
        e.preventDefault();
        $("input[name=q]").focus();
      }
    });
  })
</script>
<% end %>

app/views/shared/_parliament_issue_table.html.erb
<table class="table table-striped" data-widget="tablesorter">
  <thead>
    <tr>
      <th class="wide-table-header"><%= ParliamentIssue.human_attribute_name :last_update %></th>
      <th><%= ParliamentIssue.human_attribute_name :summary %></th>
      <th><%= ParliamentIssue.human_attribute_name :status %></th>
    </tr>
  </thead>

  <tbody>
      <% parliament_issues.each do |parliament_issue| %>
      <tr>
        <td><%= parliament_issue.last_update_text %></td>
        <td><%= link_to parliament_issue.summary, parliament_issue %></td>
        <td><%= parliament_issue.status_text %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/shared/_previous_next_links.html.erb
<div class="row-fluid issue-navigation">
  <% if previous_item %>
    <p class="pull-left">
      <%= link_to previous_item do %>
        &larr; <%= previous_item.read_attribute(item_text_attr) %>
      <% end %>
    </p>
  <% end %>

  <% if next_item %>
    <p class="pull-right">
      <%= link_to next_item do %>
        <%= next_item.read_attribute(item_text_attr) %> &rarr;
      <% end %>
    </p>
  <% end %>
</div>

app/views/shared/_promises_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= ParliamentPeriod.model_name.human.capitalize %></th>
      <th><%= Promise.human_attribute_name :party %></th>
      <th><%= Promise.human_attribute_name :body %></th>
      <th><%= Promise.human_attribute_name :source %></th>
      <th><%= Category.model_name.human(count: 2).capitalize %></th>
    </tr>
  </thead>

  <tbody>
    <% promises.each do |promise| %>
      <tr>
        <td><%= promise.parliament_period_name %></td>
        <td>
          <% promise.parties.each do |party| %>
            <%= link_to party.name, party %>
          <% end %>

          <% if promise.promisor.kind_of? Government %>
            (<%= promise.promisor.name %>)
          <% end %>
        </td>
        <td><%= promise.body %></td>
        <td><%= promise.source %></td>
        <td>
          <% promise.categories.each do |c| %>
            <%= link_to c.name, c %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_propositions_feed.html.erb
<div class="proposition-feed" style="<%= "height: #{feed.height}" if feed.height %>">
  <h4><%= feed.title %></h4>

  <div class="proposition-list">
    <% feed.propositions.each do |prop| %>
      <%= link_to proposition_path(prop), class: 'proposition', data: {id: prop.id} do %>
        <div class="row-fluid">
          <div class="span9"><%= prop.title %></div>
          <time class="span3 muted"><%= prop.datestamp %></time>
        </div>

        <% if feed.show_proposers? && prop.proposers.any? %>
          <div class="row-fluid">
              <small class="muted"><%= prop.proposers.to_sentence %></small>
          </div>
        <% end %>

        <% if feed.show_parties? %>
          <div class="row-fluid positions muted">
            <div class="span4 position-support">
              <div><strong>For</strong></div>
              <%= prop.supporters.map(&:external_id).join(' ') %>
            </div>

            <div class="span4 position-absent">
              <% if prop.absentees.any? %>
                <div><strong>Fraværende</strong></div>
                <%= prop.absentees.map(&:external_id).join(' ') %>
              <% end %>
            </div>    

            <div class="span4 position-oppose">
              <div><strong>Mot</strong></div>
              <%= prop.opposers.map(&:external_id).join(' ') %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <% if feed.see_all? %>
      <small class="see-all"><%= link_to 'Se alle forslag &raquo;'.html_safe, propositions_path %></small>
    <% end %>
  </div>
</div>

app/views/shared/_question_card.html.erb
<%= link_to question, class: 'question' do %>
  <div class="avatar-container">
    <img src="<%= path_to_image question.representative_avatar %>" class="representative" alt="<%= question.representative_name %>">
    <%= image_tag question.party_logo, alt: question.party_name, class: "party-logo" %>
  </div>
  <p><%= question.teaser(local_assigns.fetch(:teaser_length, 100)) %></p>
  <aside class="muted">
    <div>
      Fra <%= question.from_display_name %>
      til <%= question.representative_name %>
      fra <span class="district"><%= question.district_name %></span>
    </div>
    <!-- TODO: uncomment this when activity is high so it looks good.
    <div><%= question.status_description %></div>
    -->
  </aside>
<% end %>

app/views/shared/_representatives_table.html.erb
<p class="pull-right"><%= t('app.counts.representative', :count => representatives.size).html_safe %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Representative.human_attribute_name :name %></th>

      <% if show_party %>
        <th><%= Representative.human_attribute_name :party %></th>
      <% end %>

      <% if show_district %>
        <th><%= Representative.human_attribute_name :district %></th>
      <% end %>

      <th>Møtende</th>
      <th>Vara</th>
    </tr>
  </thead>
  <tbody>
      <% representatives.each do |rep| %>
      <tr>
        <td><%= link_to rep.display_name, rep %></td>

        <% if show_party && rep.latest_party %>
          <td><%= link_to rep.latest_party.name, rep.latest_party %></td>
        <% end %>

        <% if show_district %>
          <td><%= link_to rep.district.name, rep.district %></td>
        <% end %>

        <td><% if rep.attending? %>&#9733;<% end %></td>
        <td><% if rep.substitute? %>&#9733;<% end %></td>
      </tr>

      <% end %>
  </tbody>
</table>

app/views/shared/_social_sharing.html.erb
<div class="social">
  <a href="https://twitter.com/share" class="twitter-share-button" data-via="holderdeord" data-lang="no" data-dnt="true">Tweet</a>
  <div class="fb-like" data-layout="button_count" data-send="false" data-show-faces="false" data-font="arial" data-action="recommend"></div>
</div>

app/views/shared/_votes_summary_table.html.erb
<% if votes.any? %>
  <table id="votes" class="table table-striped">
    <thead>
      <tr>
        <th class="wide-table-header"><%= Vote.human_attribute_name :external_id %></th>
        <th class="wide-table-header"><%= Vote.human_attribute_name :time %></th>
        <% if show_issues %>
          <th><%= ParliamentIssue.model_name.human(count: 2).capitalize %></th>
        <% end %>
        <th><%= Vote.human_attribute_name :subject %></th>
        <th><%= Vote.human_attribute_name :enacted %></th>
        <th class="wide-table-header"><%= Vote.human_attribute_name :for_count %></th>
        <th class="wide-table-header"><%= Vote.human_attribute_name :against_count %></th>
        <th class="wide-table-header"><%= Vote.human_attribute_name :absent_count %></th>
      </tr>
    </thead>
    <tbody>
      <% votes.each do |vote| %>
      <tr>
        <td><%= vote.external_id %></td>
        <td><%= l vote.time.localtime, format: :short_text %></td>
        <% if show_issues %>
          <td>
            <ul>
              <%- vote.parliament_issues.each do |parliament_issue| -%>
              <li><%= link_to parliament_issue.summary, parliament_issue %></li>
              <%- end -%>
            </ul>

          </td>
        <% end %>
        <td><%= link_to vote.subject, vote %></td>
        <td><%= vote.enacted_text %></td>

        <% stats = vote.stats %>
        <td class="vote-for"><%= stats.for_percent %>% (<%= stats.for_count %>/<%= stats.vote_count %>)</td>
        <td class="vote-against"><%= stats.against_percent %>% (<%= stats.against_count %>/<%= stats.vote_count %>)</td>
        <td class="vote-absent"><%= stats.absent_percent %>% (<%= vote.absent_count %>/<%= stats.total_count %>)</td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>